spring:
 rabbitmq:
    host: 192.168.31.20
    port: 5672
    username: admin
    password: 123
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
       mandatory: true
    listener:
     simple:
        acknowledge-mode: manual
server:
    port: 8062


