spring:
  profiles:
    active: prod
generator:
  dataBaseName: md_iot_safety
  entityFtlPath: /com/example/generator/ftl/demo1.ftl
  xmlFtlPath: /com/example/generator/ftl/demo2.ftl
  entityFilePath: C:\Users\Ueno\IdeaProjects\Parent\Common\src\main\java\com\yao\entity\
  xmlFilePath: src/main/resources/mapper/
  entityQuote: com.yao.entity
  mapperQuote: com.example.generator.mapper
  pagePrefix: com.example.generator